from datetime import datetime, timezone
from pathlib import Path

import structlog
from docx import Document
from docx.shared import Inches, Pt

logger = structlog.get_logger()


def build_brief_docx(
    title: str,
    client_name: str,
    content_markdown: str,
    output_dir: str = "./data/drafts",
) -> Path:
    """Build a meeting brief .docx file and return its path."""
    out_dir = Path(output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    doc = Document()
    for section in doc.sections:
        section.top_margin = Inches(1)
        section.bottom_margin = Inches(1)
        section.left_margin = Inches(1)
        section.right_margin = Inches(1)

    # Header
    header = doc.sections[0].header
    header.paragraphs[0].text = f"CopInvest  |  Meeting Brief  |  {client_name}"

    # Footer
    footer = doc.sections[0].footer
    footer.paragraphs[0].text = (
        "DRAFT — generated by CopInvest for adviser review. "
        "Not for distribution to clients without approval."
    )

    # Title
    title_para = doc.add_paragraph()
    run = title_para.add_run(f"Meeting Brief: {title}")
    run.bold = True
    run.font.size = Pt(16)

    # Metadata
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    doc.add_paragraph(f"Client: {client_name}")
    doc.add_paragraph(f"Generated: {ts}")

    doc.add_paragraph()  # spacer

    # Content
    for line in content_markdown.split("\n"):
        line = line.strip()
        if not line:
            continue
        if line.startswith("# "):
            p = doc.add_paragraph()
            r = p.add_run(line[2:])
            r.bold = True
            r.font.size = Pt(14)
        elif line.startswith("## "):
            p = doc.add_paragraph()
            r = p.add_run(line[3:])
            r.bold = True
            r.font.size = Pt(12)
        elif line.startswith("- "):
            doc.add_paragraph(line[2:], style="List Bullet")
        elif line.startswith("1. ") or line.startswith("2. "):
            doc.add_paragraph(line[3:], style="List Number")
        else:
            doc.add_paragraph(line)

    ts_file = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
    filename = f"brief_{client_name.replace(' ', '_')}_{ts_file}.docx"
    out_path = out_dir / filename
    doc.save(out_path)

    logger.info("brief_docx_built", client=client_name, path=str(out_path))
    return out_path
