"""add document registry

Revision ID: 23b31f0ac9b4
Revises: 0f1eb48835fc
Create Date: 2026-05-06 19:30:07.730154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23b31f0ac9b4'
down_revision: Union[str, Sequence[str], None] = '0f1eb48835fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_registry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.String(length=255), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('doc_type', sa.String(length=50), nullable=False),
    sa.Column('sensitivity_tier', sa.Integer(), nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('total_chars', sa.Integer(), nullable=False),
    sa.Column('warnings', sa.Text(), nullable=True),
    sa.Column('parse_duration_ms', sa.Integer(), nullable=False),
    sa.Column('extraction_method', sa.String(length=100), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingested_by', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['ingested_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_registry_document_id'), 'document_registry', ['document_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_registry_document_id'), table_name='document_registry')
    op.drop_table('document_registry')
    # ### end Alembic commands ###
